<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.10.0" xml:lang="en-US">
  <compounddef id="classutils_1_1exceptions_1_1PlayerWithSameNameError" kind="class" language="Python" prot="public">
    <compoundname>utils::exceptions::PlayerWithSameNameError</compoundname>
    <basecompoundref prot="public" virt="non-virtual">Exception</basecompoundref>
    <sectiondef kind="public-func">
      <memberdef kind="function" id="classutils_1_1exceptions_1_1PlayerWithSameNameError_1a4d93bbc2a4e48fc575fdad48848104a1" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type></type>
        <definition>utils.exceptions.PlayerWithSameNameError.__init__</definition>
        <argsstring>(self, message=&quot;Your current player name is already taken, please change it.&quot;)</argsstring>
        <name>__init__</name>
        <qualifiedname>utils.exceptions.PlayerWithSameNameError.__init__</qualifiedname>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <param>
          <type>message</type>
          <defname>message</defname>
          <defval>&quot;Your current player name is already taken, please change it.&quot;</defval>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="/home/samuel/Documents/Python/Tile-Game/game/utils/exceptions.py" line="54" column="1" bodyfile="/home/samuel/Documents/Python/Tile-Game/game/utils/exceptions.py" bodystart="54" bodyend="56"/>
      </memberdef>
    </sectiondef>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
<para><verbatim>Class for creating the exception caused by joining a server with an in-game name that is already taken.
</verbatim> </para>
    </detaileddescription>
    <inheritancegraph>
      <node id="2">
        <label>Exception</label>
      </node>
      <node id="1">
        <label>utils.exceptions.PlayerWithSameNameError</label>
        <link refid="classutils_1_1exceptions_1_1PlayerWithSameNameError"/>
        <childnode refid="2" relation="public-inheritance">
        </childnode>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="2">
        <label>Exception</label>
      </node>
      <node id="1">
        <label>utils.exceptions.PlayerWithSameNameError</label>
        <link refid="classutils_1_1exceptions_1_1PlayerWithSameNameError"/>
        <childnode refid="2" relation="public-inheritance">
        </childnode>
      </node>
    </collaborationgraph>
    <location file="/home/samuel/Documents/Python/Tile-Game/game/utils/exceptions.py" line="49" column="1" bodyfile="/home/samuel/Documents/Python/Tile-Game/game/utils/exceptions.py" bodystart="49" bodyend="56"/>
    <listofallmembers>
      <member refid="classutils_1_1exceptions_1_1PlayerWithSameNameError_1a4d93bbc2a4e48fc575fdad48848104a1" prot="public" virt="non-virtual"><scope>utils::exceptions::PlayerWithSameNameError</scope><name>__init__</name></member>
    </listofallmembers>
  </compounddef>
</doxygen>
