<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<section xmlns="http://docbook.org/ns/docbook" version="5.0" xmlns:xlink="http://www.w3.org/1999/xlink" xml:id="_classgame_1_1utils_1_1exceptions_1_1InvalidGamePropertyValue" xml:lang="en-US">
<title>game.utils.exceptions.InvalidGamePropertyValue Class Reference</title>
<indexterm><primary>game.utils.exceptions.InvalidGamePropertyValue</primary></indexterm>
<para>Inheritance diagram for game.utils.exceptions.InvalidGamePropertyValue:    <informalfigure>
        <mediaobject>
            <imageobject>
                <imagedata width="50%" align="center" valign="middle" scalefit="0" fileref="classgame_1_1utils_1_1exceptions_1_1InvalidGamePropertyValue.png"></imagedata>
            </imageobject>
        </mediaobject>
    </informalfigure>
</para>
<simplesect>
    <title>Public Member Functions    </title>
        <itemizedlist>
            <listitem><para><link linkend="_classgame_1_1utils_1_1exceptions_1_1InvalidGamePropertyValue_1a733510c07e5b2effe96c7eddea99c088">__init__</link> (self, message)</para>
</listitem>
        </itemizedlist>
</simplesect>
<section>
<title>Detailed Description</title>

<para><literallayout><computeroutput>Class for creating the exception caused by an invalid game property value.
</computeroutput></literallayout> </para>
</section>
<section>
<title>Constructor &amp; Destructor Documentation</title>
<anchor xml:id="_classgame_1_1utils_1_1exceptions_1_1InvalidGamePropertyValue_1a733510c07e5b2effe96c7eddea99c088"/><section>
    <title>__init__()</title>
<indexterm><primary>__init__</primary><secondary>game.utils.exceptions.InvalidGamePropertyValue</secondary></indexterm>
<indexterm><primary>game.utils.exceptions.InvalidGamePropertyValue</primary><secondary>__init__</secondary></indexterm>
<para><computeroutput>game.utils.exceptions.InvalidGamePropertyValue.__init__ ( self,  message)</computeroutput></para></section>
<para>
The documentation for this class was generated from the following file:</para>
<link linkend="_exceptions_8py">exceptions.py</link></section>
</section>
